include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
    # Explanation: https://dash-overflow.net/articles/getting_started/
  errors:
    # treat missing required parameters as an error (not a hint)
    missing_required_param: error
    # treat missing returns as an error (not a hint)
    missing_return: error
    invalid_annotation_target: ignore
  exclude:
    - lib/**/*.g.dart
    - lib/*.g.dart
    - lib/**/*.graphql.dart
    - lib/**/*.freezed.dart
    - test/**/*.mocks.dart
  language:
    strict-casts: true
    # strict-raw-types: true # I want this one enabled, and we should work toward that. @hans

linter:
  rules:
    avoid_dynamic_calls: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    use_key_in_widget_constructors: true
    sort_child_properties_last: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    avoid_void_async: true
    unnecessary_parenthesis: true
    always_declare_return_types: true
    unawaited_futures: true
    only_throw_errors: true
    missing_whitespace_between_adjacent_strings: true
    sized_box_for_whitespace: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_constructors_in_immutables: true
    no_logic_in_create_state: true
    avoid_unnecessary_containers: true
    avoid_print: true
    avoid_relative_lib_imports: true
    empty_statements: true
    no_adjacent_strings_in_list: true
    no_duplicate_case_values: true
    valid_regexps: true
    require_trailing_commas: true

    avoid_function_literals_in_foreach_calls: false
